# Generated by Django 3.2.9 on 2022-02-24 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_wow', '0002_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='time',
            old_name='time',
            new_name='hour',
        ),
    ]
