# Generated by Django 3.2.9 on 2022-02-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_wow', '0003_rename_time_time_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='image',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='time',
            name='upload',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
