# Generated by Django 3.2.9 on 2022-02-28 11:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_wow', '0006_auto_20220225_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
